services:
  - type: web
    runtime: docker
    name: phantichnhadathcm
    region: singapore
    plan: free
    dockerfilePath: ./deploy/Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: BDS_APP_HOST
        value: 0.0.0.0
